version: "3"
services:
  web:
    restart: always
    build: .
    links:
      - redis
    ports:
      - "1443:1443"
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
    restart: always
  selenium-firefox:
    image: b4handjr/selenium-firefox
    restart: always
    ports:
      - "${VNC_PORT:-5900}:5900"
    shm_size: 2g
    volumes:
      - .:/code
